### ISSUE TITLE
SWS 2900 Help

### ISSUE THREAD

**Issue by janvrska** [erkobg/Sencor-SWS-THS#2]
I have Sencor SWS 2900, and I am not able to make it work with your library.
Personally, I think there is a problem in my timing like sync,bit0,bit1,glitch.
Can you please look on my measure which i directly captured with Audacity from my sensor by linein to my sound card and write me correct timings from my capture to your library
Thank you

[capture.zip](https://github.com/erkobg/Sencor-SWS-THS/files/3780278/capture.zip)

**Comment by erkobg** [comment]
Hello,
for better analyses of the signal - can you address it here: https://github.com/Martin-Laclaustra/rc-switch 


Regards

**Comment by erkobg** [comment]
Can you ask for analyses here : https://github.com/Martin-Laclaustra/rc-switch
